AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Layout/LineLength:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
